######################################################################
# Automatically generated by qmake (3.0) ? 3? 31 21:50:41 2016
######################################################################

TEMPLATE = app
TARGET = score-sl-stage
INCLUDEPATH += .
QT += qml quick widgets gui
QMAKE_CXXFLAGS += -g -O0

# Input
SOURCES += main.cpp ScoreDrawing.cpp ScorePage.cpp
HEADERS += ScoreDrawing.h ScorePage.h
